#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on:  10 September 2021                  #
#-------------------------------------------------#
# Topic:       Magnus effect                      #
# OpenFOAM:    version 9 (Foundation)             #
#-------------------------------------------------#
# Website:     https://Holzmann-cfd.com           #
# Email:       community@Holzmann-cfd.com         #
#-------------------------------------------------#


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-9"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble


#------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#------------------------------------------------------------------------------
echo -e "   - Create background mesh"
blockMesh
# ideasUnvToFoam cad/backgroundMesh.unv > logFile
# transformPoints "scale=(16.0 16.0 1.0)"  >> logFile
# refineMesh -overwrite
# refineMesh -overwrite
# refineMesh -overwrite

#------------------------------------------------------------------------------
echo -e "   - Meshing with snappyHexMesh"
snappyHexMesh -overwrite >> logFile
# exit


#------------------------------------------------------------------------------
echo -e "   - Extrude one patch to make a 2D mesh"
extrudeMesh  >> logFile


#------------------------------------------------------------------------------
echo -e "   - Change patch type in the boundary file"
changeDictionary  >> logFile


#------------------------------------------------------------------------------
# echo -e "   - Translate mesh to point (0 0 0)"
# transformPoints "translate=(1.2 -2.4375 -0.1)"  >> logFile


#------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n
"


#------------------------------------------------------------------------------
echo -e "   - Copy 0.org to 0"
rm -r 0
cp -r 0.orig 0


#------------------------------------------------------------------------------
echo -e "   - Start simulation"
decomposePar
mpirun -np 6 pisoFoam -parallel >logFile #/dev/null
reconstructPar
#pisoFoam >/dev/null #logFile

#------------------------------------------------------------------------------
echo -e "   - Simulation ended\n\n"


#------------------------------------------------------------------------------
